spring.application.name=lms-user-service
info.app.version=1.0.0
APP_ENV=${APP_ENV}
#DB connections
AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
AWS_DYNAMODB_ROLES_TABLE_NAME=${AWS_DYNAMODB_ROLES_TABLE_NAME}
AWS_DYNAMODB_ROLES_PARTITION_KEY_NAME=${AWS_DYNAMODB_ROLES_PARTITION_KEY_NAME}
AWS_DYNAMODB_USER_TABLE_DEFAULT_SORT_KEY=${AWS_DYNAMODB_USER_TABLE_DEFAULT_SORT_KEY}
AWS_DYNAMODB_USER_TABLE_DEFAULT_SORT_ORDER=${AWS_DYNAMODB_USER_TABLE_DEFAULT_SORT_ORDER}
AWS_DYNAMODB_USER_TABLE_NAME=${AWS_DYNAMODB_USER_TABLE_NAME}
AWS_DYNAMODB_USER_TABLE_PARTITION_KEY_NAME=${AWS_DYNAMODB_USER_TABLE_PARTITION_KEY_NAME}
REGION_NAME=${REGION_NAME}
#Storing in S3
AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
#Storing in Local
LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
#Cognito User Pool ID
AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
AWS_DYNAMODB_LOGFILE_TABLE_NAME=${AWS_DYNAMODB_LOGFILE_TABLE_NAME}
AWS_DYNAMODB_LOGFILE_TABLE_PARTITION_KEY_NAME=${AWS_DYNAMODB_LOGFILE_TABLE_PARTITION_KEY_NAME}
AWS_DYNAMODB_LOGFILE_TABLE_DEFAULT_SORT_KEY=${AWS_DYNAMODB_LOGFILE_TABLE_DEFAULT_SORT_KEY}
AWS_DYNAMODB_LOGFILE_TABLE_DEFAULT_SORT_ORDER=${AWS_DYNAMODB_LOGFILE_TABLE_DEFAULT_SORT_ORDER}
AWS_DYNAMODB_TENANT_TABLE_NAME=${AWS_DYNAMODB_TENANT_TABLE_NAME}
AWS_SQS_QUEUE_URL=${AWS_SQS_QUEUE_URL}
LMS_ADMIN_EMAIL=${LMS_ADMIN_EMAIL}
LMS_FROM_EMAIL_ADDRESS=${LMS_FROM_EMAIL_ADDRESS}
LMS_URL=${LMS_URL}
AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
AWS_COGNITO_CLIENT_SECRET=${AWS_COGNITO_CLIENT_SECRET}
AWS_COGNITO_DOMAIN=${AWS_COGNITO_DOMAIN}
AWS_COGNITO_ISSUER=${AWS_COGNITO_ISSUER}
AWS_COGNITO_CERT_URL=${AWS_COGNITO_CERT_URL}
COURSE_MANAGEMENT_SERVICE_API_URL=${COURSE_MANAGEMENT_SERVICE_API_URL}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#logging.level.org.springframework=DEBUG
AWS_DYNAMODB_COUNTRY_TABLE_NAME=${AWS_DYNAMODB_COUNTRY_TABLE_NAME}
AWS_DYNAMODB_LOOKUP_TABLE_NAME=${AWS_DYNAMODB_LOOKUP_TABLE_NAME}
AWS_DYNAMODB_USER_GLOBAL_SEARCH_HISTORY_TABLE_NAME = ${AWS_DYNAMODB_USER_GLOBAL_SEARCH_HISTORY_TABLE_NAME}
AWS_DYNAMODB_USER_ACTIVITY_LOG_TABLE_NAME=${AWS_DYNAMODB_USER_ACTIVITY_LOG_TABLE_NAME}

#AWS_DYNAMODB_COUNTRY_TABLE_NAME=${AWS_DYNAMODB_COUNTRY_TABLE_NAME}
AWS_USER_MANAGEMENT_EVENT_DETAIL_TYPE = ${AWS_USER_MANAGEMENT_EVENT_DETAIL_TYPE}
AWS_USER_MANAGEMENT_EVENT_SOURCE = ${AWS_USER_MANAGEMENT_EVENT_SOURCE}
AWS_USER_MANAGEMENT_EVENT_BUS_ARN = ${AWS_USER_MANAGEMENT_EVENT_BUS_ARN}
